name: Matrix post-push
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: upload conan package to server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            conan remote add conan_packages http://188.225.84.75:9300;
            conan remote login conan_packages;
            conan upload matrix/1.0@ --remote conan_packages
