name: Matrix pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: checkout repository
          uses: actions/checkout@v3

        - name: install uv
          uses: astral-sh/setup-uv@v5

        - name: set common environment
          run: |
            uv venv
            source .venv/bin/activate
            uv sync
            {
              echo "VIRTUAL_ENV=$VIRTUAL_ENV"
            } >> "$GITHUB_ENV"
        
        - name: install conan
          run: |
            uv pip install conan
            uv run conan profile detect --force

        - name: CMake release config
          run: |
            conan install . --build=missing s compiler.cppstd=gnu20 -s build_type=Release;
            cmake . -B build -DCMAKE_BUILD_TYPE=Release;
            cmake --build build

        - name: CMake release test
          run: ctest --test-dir build --rerun-failed --output-on-failure

        - name: CMake debug config
          run: |
            conan install . --build=missing s compiler.cppstd=gnu20 -s build_type=Debug;
            cmake . -B build -DCMAKE_BUILD_TYPE=Debug;
            cmake --build build

        - name: CMake debug test
          run: ctest --test-dir build --rerun-failed --output-on-failure