name: matrix pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: set python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install python requirements
      run: python3 -m pip install --upgrade pip setuptools wheel
    - name: update submodules
      run: git submodule update --init --recursive
    - name: CMake release config
      run: cmake . -B build -DCMAKE_BUILD_TYPE=Release; cmake --build build
    - name: CMake release test
      run: ctest --test-dir build --rerun-failed --output-on-failure
    - name: CMake debug config
      run: cmake . -B build -DCMAKE_BUILD_TYPE=Debug; cmake --build build
    - name: CMake debug test
      run: ctest --test-dir build --rerun-failed --output-on-failure